module Evergreen.Migrate.V136 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import AssocList
import Dict
import Evergreen.V135.Email
import Evergreen.V135.EmailAddress
import Evergreen.V135.Id
import Evergreen.V135.KeyValueStore
import Evergreen.V135.Name
import Evergreen.V135.Route
import Evergreen.V135.Session
import Evergreen.V135.Stripe.Codec
import Evergreen.V135.Stripe.Product
import Evergreen.V135.Stripe.PurchaseForm
import Evergreen.V135.Stripe.Stripe
import Evergreen.V135.Token.Types
import Evergreen.V135.Types
import Evergreen.V135.User
import Evergreen.V136.Email
import Evergreen.V136.EmailAddress
import Evergreen.V136.Id
import Evergreen.V136.KeyValueStore
import Evergreen.V136.Name
import Evergreen.V136.Route
import Evergreen.V136.Session
import Evergreen.V136.Stripe.Codec
import Evergreen.V136.Stripe.Product
import Evergreen.V136.Stripe.PurchaseForm
import Evergreen.V136.Stripe.Stripe
import Evergreen.V136.Token.Types
import Evergreen.V136.Types
import Evergreen.V136.User
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V135.Types.FrontendModel -> ModelMigration Evergreen.V136.Types.FrontendModel Evergreen.V136.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V135.Types.BackendModel -> ModelMigration Evergreen.V136.Types.BackendModel Evergreen.V136.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V135.Types.FrontendMsg -> MsgMigration Evergreen.V136.Types.FrontendMsg Evergreen.V136.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V135.Types.ToBackend -> MsgMigration Evergreen.V136.Types.ToBackend Evergreen.V136.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V135.Types.BackendMsg -> MsgMigration Evergreen.V136.Types.BackendMsg Evergreen.V136.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V135.Types.ToFrontend -> MsgMigration Evergreen.V136.Types.ToFrontend Evergreen.V136.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_AssocList_Dict : (a_old -> a_new) -> (b_old -> b_new) -> AssocList.Dict a_old b_old -> AssocList.Dict a_new b_new
migrate_AssocList_Dict migrate_a migrate_b old =
    old
        |> AssocList.toList
        |> List.map (Tuple.mapBoth migrate_a migrate_b)
        |> AssocList.fromList


migrate_EmailAddress_EmailAddress : Evergreen.V135.EmailAddress.EmailAddress -> Evergreen.V136.EmailAddress.EmailAddress
migrate_EmailAddress_EmailAddress old =
    case old of
        Evergreen.V135.EmailAddress.EmailAddress p0 ->
            Evergreen.V136.EmailAddress.EmailAddress p0


migrate_Email_EmailResult : Evergreen.V135.Email.EmailResult -> Evergreen.V136.Email.EmailResult
migrate_Email_EmailResult old =
    case old of
        Evergreen.V135.Email.SendingEmail ->
            Evergreen.V136.Email.SendingEmail

        Evergreen.V135.Email.EmailSuccess p0 ->
            Evergreen.V136.Email.EmailSuccess (p0 |> migrate_Email_PostmarkSendResponse)

        Evergreen.V135.Email.EmailFailed p0 ->
            Evergreen.V136.Email.EmailFailed p0


migrate_Email_PostmarkSendResponse : Evergreen.V135.Email.PostmarkSendResponse -> Evergreen.V136.Email.PostmarkSendResponse
migrate_Email_PostmarkSendResponse old =
    old


migrate_Id_Id : (a_old -> a_new) -> Evergreen.V135.Id.Id a_old -> Evergreen.V136.Id.Id a_new
migrate_Id_Id migrate_a old =
    case old of
        Evergreen.V135.Id.Id p0 ->
            Evergreen.V136.Id.Id p0


migrate_KeyValueStore_KVDatum : Evergreen.V135.KeyValueStore.KVDatum -> Evergreen.V136.KeyValueStore.KVDatum
migrate_KeyValueStore_KVDatum old =
    old


migrate_KeyValueStore_KVVerbosity : Evergreen.V135.KeyValueStore.KVVerbosity -> Evergreen.V136.KeyValueStore.KVVerbosity
migrate_KeyValueStore_KVVerbosity old =
    case old of
        Evergreen.V135.KeyValueStore.KVVerbose ->
            Evergreen.V136.KeyValueStore.KVVerbose

        Evergreen.V135.KeyValueStore.KVQuiet ->
            Evergreen.V136.KeyValueStore.KVQuiet


migrate_KeyValueStore_KVViewType : Evergreen.V135.KeyValueStore.KVViewType -> Evergreen.V136.KeyValueStore.KVViewType
migrate_KeyValueStore_KVViewType old =
    case old of
        Evergreen.V135.KeyValueStore.KVRaw ->
            Evergreen.V136.KeyValueStore.KVRaw

        Evergreen.V135.KeyValueStore.KVVSummary ->
            Evergreen.V136.KeyValueStore.KVVSummary

        Evergreen.V135.KeyValueStore.KVVKey ->
            Evergreen.V136.KeyValueStore.KVVKey


migrate_Name_Name : Evergreen.V135.Name.Name -> Evergreen.V136.Name.Name
migrate_Name_Name old =
    case old of
        Evergreen.V135.Name.Name p0 ->
            Evergreen.V136.Name.Name p0


migrate_Route_Route : Evergreen.V135.Route.Route -> Evergreen.V136.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V135.Route.HomepageRoute ->
            Evergreen.V136.Route.HomepageRoute

        Evergreen.V135.Route.DataStore ->
            Evergreen.V136.Route.DataStore

        Evergreen.V135.Route.EditData ->
            Evergreen.V136.Route.EditData

        Evergreen.V135.Route.Features ->
            Evergreen.V136.Route.Features

        Evergreen.V135.Route.TermsOfServiceRoute ->
            Evergreen.V136.Route.TermsOfServiceRoute

        Evergreen.V135.Route.Notes ->
            Evergreen.V136.Route.Notes

        Evergreen.V135.Route.SignInRoute ->
            Evergreen.V136.Route.SignInRoute

        Evergreen.V135.Route.Brillig ->
            Evergreen.V136.Route.Brillig

        Evergreen.V135.Route.AdminRoute ->
            Evergreen.V136.Route.AdminRoute

        Evergreen.V135.Route.Purchase ->
            Evergreen.V136.Route.Purchase

        Evergreen.V135.Route.PaymentSuccessRoute p0 ->
            Evergreen.V136.Route.PaymentSuccessRoute (p0 |> Maybe.map migrate_EmailAddress_EmailAddress)

        Evergreen.V135.Route.PaymentCancelRoute ->
            Evergreen.V136.Route.PaymentCancelRoute


migrate_Session_Interaction : Evergreen.V135.Session.Interaction -> Evergreen.V136.Session.Interaction
migrate_Session_Interaction old =
    case old of
        Evergreen.V135.Session.ISignIn p0 ->
            Evergreen.V136.Session.ISignIn p0

        Evergreen.V135.Session.ISignOut p0 ->
            Evergreen.V136.Session.ISignOut p0

        Evergreen.V135.Session.ISignUp p0 ->
            Evergreen.V136.Session.ISignUp p0


migrate_Session_SessionInfo : Evergreen.V135.Session.SessionInfo -> Evergreen.V136.Session.SessionInfo
migrate_Session_SessionInfo old =
    old |> Dict.map (\k -> migrate_Session_Interaction)


migrate_Stripe_Codec_Order : Evergreen.V135.Stripe.Codec.Order -> Evergreen.V136.Stripe.Codec.Order
migrate_Stripe_Codec_Order old =
    { priceId = old.priceId |> migrate_Id_Id migrate_Stripe_Stripe_PriceId
    , submitTime = old.submitTime
    , form = old.form |> migrate_Stripe_PurchaseForm_PurchaseFormValidated
    , emailResult = old.emailResult |> migrate_Email_EmailResult
    }


migrate_Stripe_Codec_PendingOrder : Evergreen.V135.Stripe.Codec.PendingOrder -> Evergreen.V136.Stripe.Codec.PendingOrder
migrate_Stripe_Codec_PendingOrder old =
    { priceId = old.priceId |> migrate_Id_Id migrate_Stripe_Stripe_PriceId
    , submitTime = old.submitTime
    , form = old.form |> migrate_Stripe_PurchaseForm_PurchaseFormValidated
    , sessionId = old.sessionId
    }


migrate_Stripe_Codec_Price2 : Evergreen.V135.Stripe.Codec.Price2 -> Evergreen.V136.Stripe.Codec.Price2
migrate_Stripe_Codec_Price2 old =
    { priceId = old.priceId |> migrate_Id_Id migrate_Stripe_Stripe_PriceId
    , price = old.price |> migrate_Stripe_Stripe_Price
    }


migrate_Stripe_Product_Product_ : Evergreen.V135.Stripe.Product.Product_ -> Evergreen.V136.Stripe.Product.Product_
migrate_Stripe_Product_Product_ old =
    old


migrate_Stripe_PurchaseForm_PressedSubmit : Evergreen.V135.Stripe.PurchaseForm.PressedSubmit -> Evergreen.V136.Stripe.PurchaseForm.PressedSubmit
migrate_Stripe_PurchaseForm_PressedSubmit old =
    case old of
        Evergreen.V135.Stripe.PurchaseForm.PressedSubmit ->
            Evergreen.V136.Stripe.PurchaseForm.PressedSubmit

        Evergreen.V135.Stripe.PurchaseForm.NotPressedSubmit ->
            Evergreen.V136.Stripe.PurchaseForm.NotPressedSubmit


migrate_Stripe_PurchaseForm_PurchaseData : Evergreen.V135.Stripe.PurchaseForm.PurchaseData -> Evergreen.V136.Stripe.PurchaseForm.PurchaseData
migrate_Stripe_PurchaseForm_PurchaseData old =
    { billingName = old.billingName |> migrate_Name_Name
    , billingEmail = old.billingEmail |> migrate_EmailAddress_EmailAddress
    }


migrate_Stripe_PurchaseForm_PurchaseForm : Evergreen.V135.Stripe.PurchaseForm.PurchaseForm -> Evergreen.V136.Stripe.PurchaseForm.PurchaseForm
migrate_Stripe_PurchaseForm_PurchaseForm old =
    { submitStatus = old.submitStatus |> migrate_Stripe_PurchaseForm_SubmitStatus
    , name = old.name
    , billingEmail = old.billingEmail
    , country = old.country
    }


migrate_Stripe_PurchaseForm_PurchaseFormValidated : Evergreen.V135.Stripe.PurchaseForm.PurchaseFormValidated -> Evergreen.V136.Stripe.PurchaseForm.PurchaseFormValidated
migrate_Stripe_PurchaseForm_PurchaseFormValidated old =
    case old of
        Evergreen.V135.Stripe.PurchaseForm.ImageCreditPurchase p0 ->
            Evergreen.V136.Stripe.PurchaseForm.ImageCreditPurchase (p0 |> migrate_Stripe_PurchaseForm_PurchaseData)

        Evergreen.V135.Stripe.PurchaseForm.ImageLibraryPackagePurchase p0 ->
            Evergreen.V136.Stripe.PurchaseForm.ImageLibraryPackagePurchase (p0 |> migrate_Stripe_PurchaseForm_PurchaseData)


migrate_Stripe_PurchaseForm_SubmitStatus : Evergreen.V135.Stripe.PurchaseForm.SubmitStatus -> Evergreen.V136.Stripe.PurchaseForm.SubmitStatus
migrate_Stripe_PurchaseForm_SubmitStatus old =
    case old of
        Evergreen.V135.Stripe.PurchaseForm.NotSubmitted p0 ->
            Evergreen.V136.Stripe.PurchaseForm.NotSubmitted (p0 |> migrate_Stripe_PurchaseForm_PressedSubmit)

        Evergreen.V135.Stripe.PurchaseForm.Submitting ->
            Evergreen.V136.Stripe.PurchaseForm.Submitting

        Evergreen.V135.Stripe.PurchaseForm.SubmitBackendError p0 ->
            Evergreen.V136.Stripe.PurchaseForm.SubmitBackendError p0


migrate_Stripe_Stripe_Price : Evergreen.V135.Stripe.Stripe.Price -> Evergreen.V136.Stripe.Stripe.Price
migrate_Stripe_Stripe_Price old =
    old


migrate_Stripe_Stripe_PriceId : Evergreen.V135.Stripe.Stripe.PriceId -> Evergreen.V136.Stripe.Stripe.PriceId
migrate_Stripe_Stripe_PriceId old =
    case old of
        Evergreen.V135.Stripe.Stripe.PriceId p0 ->
            Evergreen.V136.Stripe.Stripe.PriceId p0


migrate_Stripe_Stripe_ProductId : Evergreen.V135.Stripe.Stripe.ProductId -> Evergreen.V136.Stripe.Stripe.ProductId
migrate_Stripe_Stripe_ProductId old =
    case old of
        Evergreen.V135.Stripe.Stripe.ProductId p0 ->
            Evergreen.V136.Stripe.Stripe.ProductId p0


migrate_Stripe_Stripe_ProductInfo : Evergreen.V135.Stripe.Stripe.ProductInfo -> Evergreen.V136.Stripe.Stripe.ProductInfo
migrate_Stripe_Stripe_ProductInfo old =
    old


migrate_Stripe_Stripe_ProductInfoDict : Evergreen.V135.Stripe.Stripe.ProductInfoDict -> Evergreen.V136.Stripe.Stripe.ProductInfoDict
migrate_Stripe_Stripe_ProductInfoDict old =
    old |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_ProductId) migrate_Stripe_Stripe_ProductInfo


migrate_Stripe_Stripe_StripeSessionId : Evergreen.V135.Stripe.Stripe.StripeSessionId -> Evergreen.V136.Stripe.Stripe.StripeSessionId
migrate_Stripe_Stripe_StripeSessionId old =
    case old of
        Evergreen.V135.Stripe.Stripe.StripeSessionId p0 ->
            Evergreen.V136.Stripe.Stripe.StripeSessionId p0


migrate_Token_Types_EnterEmail2 : Evergreen.V135.Token.Types.EnterEmail2 -> Evergreen.V136.Token.Types.EnterEmail2
migrate_Token_Types_EnterEmail2 old =
    old


migrate_Token_Types_EnterLoginCode2 : Evergreen.V135.Token.Types.EnterLoginCode2 -> Evergreen.V136.Token.Types.EnterLoginCode2
migrate_Token_Types_EnterLoginCode2 old =
    { sentTo = old.sentTo |> migrate_EmailAddress_EmailAddress
    , loginCode = old.loginCode
    , attempts = old.attempts |> Dict.map (\k -> migrate_Token_Types_LoginCodeStatus)
    }


migrate_Token_Types_Log : Evergreen.V135.Token.Types.Log -> Evergreen.V136.Token.Types.Log
migrate_Token_Types_Log old =
    old |> List.map (Tuple.mapSecond migrate_Token_Types_LogItem)


migrate_Token_Types_LogItem : Evergreen.V135.Token.Types.LogItem -> Evergreen.V136.Token.Types.LogItem
migrate_Token_Types_LogItem old =
    case old of
        Evergreen.V135.Token.Types.LoginsRateLimited p0 ->
            Evergreen.V136.Token.Types.LoginsRateLimited p0

        Evergreen.V135.Token.Types.FailedToCreateLoginCode p0 ->
            Evergreen.V136.Token.Types.FailedToCreateLoginCode p0


migrate_Token_Types_LoginCodeStatus : Evergreen.V135.Token.Types.LoginCodeStatus -> Evergreen.V136.Token.Types.LoginCodeStatus
migrate_Token_Types_LoginCodeStatus old =
    case old of
        Evergreen.V135.Token.Types.Checking ->
            Evergreen.V136.Token.Types.Checking

        Evergreen.V135.Token.Types.NotValid ->
            Evergreen.V136.Token.Types.NotValid


migrate_Token_Types_LoginForm : Evergreen.V135.Token.Types.LoginForm -> Evergreen.V136.Token.Types.LoginForm
migrate_Token_Types_LoginForm old =
    case old of
        Evergreen.V135.Token.Types.EnterEmail p0 ->
            Evergreen.V136.Token.Types.EnterEmail (p0 |> migrate_Token_Types_EnterEmail2)

        Evergreen.V135.Token.Types.EnterLoginCode p0 ->
            Evergreen.V136.Token.Types.EnterLoginCode (p0 |> migrate_Token_Types_EnterLoginCode2)


migrate_Types_AdminDisplay : Evergreen.V135.Types.AdminDisplay -> Evergreen.V136.Types.AdminDisplay
migrate_Types_AdminDisplay old =
    case old of
        Evergreen.V135.Types.ADStripe ->
            Evergreen.V136.Types.ADStripe

        Evergreen.V135.Types.ADUser ->
            Evergreen.V136.Types.ADUser

        Evergreen.V135.Types.ADSession ->
            Evergreen.V136.Types.ADSession

        Evergreen.V135.Types.ADKeyValues ->
            Evergreen.V136.Types.ADKeyValues


migrate_Types_BackendModel : Evergreen.V135.Types.BackendModel -> Evergreen.V136.Types.BackendModel
migrate_Types_BackendModel old =
    { randomAtmosphericNumbers = old.randomAtmosphericNumbers
    , localUuidData = old.localUuidData
    , time = old.time
    , secretCounter = old.secretCounter
    , sessionDict = old.sessionDict
    , pendingLogins =
        old.pendingLogins
            |> migrate_AssocList_Dict identity
                (\rec ->
                    { loginAttempts = rec.loginAttempts
                    , emailAddress = rec.emailAddress |> migrate_EmailAddress_EmailAddress
                    , creationTime = rec.creationTime
                    , loginCode = rec.loginCode
                    }
                )
    , log = old.log |> migrate_Token_Types_Log
    , userDictionary = old.userDictionary |> Dict.map (\k -> migrate_User_User)
    , sessions = old.sessions
    , sessionInfo = old.sessionInfo |> migrate_Session_SessionInfo
    , orders = old.orders |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_StripeSessionId) migrate_Stripe_Codec_Order
    , pendingOrder = old.pendingOrder |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_StripeSessionId) migrate_Stripe_Codec_PendingOrder
    , expiredOrders = old.expiredOrders |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_StripeSessionId) migrate_Stripe_Codec_PendingOrder
    , prices = old.prices |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_ProductId) migrate_Stripe_Codec_Price2
    , products = old.products |> migrate_Stripe_Stripe_ProductInfoDict
    , keyValueStore = old.keyValueStore
    }


migrate_Types_FrontendModel : Evergreen.V135.Types.FrontendModel -> Evergreen.V136.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V135.Types.Loading p0 ->
            Evergreen.V136.Types.Loading (p0 |> migrate_Types_LoadingModel)

        Evergreen.V135.Types.Loaded p0 ->
            Evergreen.V136.Types.Loaded (p0 |> migrate_Types_LoadedModel)


migrate_Types_FrontendMsg : Evergreen.V135.Types.FrontendMsg -> Evergreen.V136.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V135.Types.NoOp ->
            Evergreen.V136.Types.NoOp

        Evergreen.V135.Types.UrlClicked p0 ->
            Evergreen.V136.Types.UrlClicked p0

        Evergreen.V135.Types.UrlChanged p0 ->
            Evergreen.V136.Types.UrlChanged p0

        Evergreen.V135.Types.Tick p0 ->
            Evergreen.V136.Types.Tick p0

        Evergreen.V135.Types.GotWindowSize p0 p1 ->
            Evergreen.V136.Types.GotWindowSize p0 p1

        Evergreen.V135.Types.PressedShowTooltip ->
            Evergreen.V136.Types.PressedShowTooltip

        Evergreen.V135.Types.MouseDown ->
            Evergreen.V136.Types.MouseDown

        Evergreen.V135.Types.PressedSubmitEmail ->
            Evergreen.V136.Types.PressedSubmitEmail

        Evergreen.V135.Types.PressedCancelLogin ->
            Evergreen.V136.Types.PressedCancelLogin

        Evergreen.V135.Types.TypedLoginFormEmail p0 ->
            Evergreen.V136.Types.TypedLoginFormEmail p0

        Evergreen.V135.Types.TypedLoginCode p0 ->
            Evergreen.V136.Types.TypedLoginCode p0

        Evergreen.V135.Types.SignOut ->
            Evergreen.V136.Types.SignOut

        Evergreen.V135.Types.BuyProduct p0 p1 p2 ->
            Evergreen.V136.Types.BuyProduct (p0 |> migrate_Id_Id migrate_Stripe_Stripe_ProductId)
                (p1 |> migrate_Id_Id migrate_Stripe_Stripe_PriceId)
                (p2 |> migrate_Stripe_Product_Product_)

        Evergreen.V135.Types.PressedSelectTicket p0 p1 ->
            Evergreen.V136.Types.PressedSelectTicket (p0 |> migrate_Id_Id migrate_Stripe_Stripe_ProductId)
                (p1 |> migrate_Id_Id migrate_Stripe_Stripe_PriceId)

        Evergreen.V135.Types.FormChanged p0 ->
            Evergreen.V136.Types.FormChanged (p0 |> migrate_Stripe_PurchaseForm_PurchaseForm)

        Evergreen.V135.Types.PressedSubmitForm p0 p1 ->
            Evergreen.V136.Types.PressedSubmitForm (p0 |> migrate_Id_Id migrate_Stripe_Stripe_ProductId)
                (p1 |> migrate_Id_Id migrate_Stripe_Stripe_PriceId)

        Evergreen.V135.Types.PressedCancelForm ->
            Evergreen.V136.Types.PressedCancelForm

        Evergreen.V135.Types.AskToRenewPrices ->
            Evergreen.V136.Types.AskToRenewPrices

        Evergreen.V135.Types.SubmitSignUp ->
            Evergreen.V136.Types.SubmitSignUp

        Evergreen.V135.Types.InputRealname p0 ->
            Evergreen.V136.Types.InputRealname p0

        Evergreen.V135.Types.InputUsername p0 ->
            Evergreen.V136.Types.InputUsername p0

        Evergreen.V135.Types.InputEmail p0 ->
            Evergreen.V136.Types.InputEmail p0

        Evergreen.V135.Types.CancelSignUp ->
            Evergreen.V136.Types.CancelSignUp

        Evergreen.V135.Types.SetAdminDisplay p0 ->
            Evergreen.V136.Types.SetAdminDisplay (p0 |> migrate_Types_AdminDisplay)

        Evergreen.V135.Types.SetViewport ->
            Evergreen.V136.Types.SetViewport

        Evergreen.V135.Types.LanguageChanged p0 ->
            Evergreen.V136.Types.LanguageChanged p0

        Evergreen.V135.Types.CopyTextToClipboard p0 ->
            Evergreen.V136.Types.CopyTextToClipboard p0

        Evergreen.V135.Types.Chirp ->
            Evergreen.V136.Types.Chirp

        Evergreen.V135.Types.RequestWeatherData p0 ->
            Evergreen.V136.Types.RequestWeatherData p0

        Evergreen.V135.Types.InputCity p0 ->
            Evergreen.V136.Types.InputCity p0

        Evergreen.V135.Types.InputKey p0 ->
            Evergreen.V136.Types.InputKey p0

        Evergreen.V135.Types.InputValue p0 ->
            Evergreen.V136.Types.InputValue p0

        Evergreen.V135.Types.InputFilterData p0 ->
            Evergreen.V136.Types.InputFilterData p0

        Evergreen.V135.Types.NewKeyValuePair ->
            Evergreen.V136.Types.NewKeyValuePair

        Evergreen.V135.Types.AddKeyValuePair p0 p1 ->
            Evergreen.V136.Types.AddKeyValuePair p0 (p1 |> migrate_KeyValueStore_KVDatum)

        Evergreen.V135.Types.GetValueWithKey p0 ->
            Evergreen.V136.Types.GetValueWithKey p0

        Evergreen.V135.Types.GotValueFromKVStore p0 ->
            Evergreen.V136.Types.GotValueFromKVStore p0

        Evergreen.V135.Types.DataUploaded p0 ->
            Evergreen.V136.Types.DataUploaded p0

        Evergreen.V135.Types.SetKVViewType p0 ->
            Evergreen.V136.Types.SetKVViewType (p0 |> migrate_KeyValueStore_KVViewType)

        Evergreen.V135.Types.CycleKVVerbosity p0 ->
            Evergreen.V136.Types.CycleKVVerbosity (p0 |> migrate_KeyValueStore_KVVerbosity)


migrate_Types_InitData2 : Evergreen.V135.Types.InitData2 -> Evergreen.V136.Types.InitData2
migrate_Types_InitData2 old =
    { prices =
        old.prices
            |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_ProductId)
                (\rec ->
                    { priceId = rec.priceId |> migrate_Id_Id migrate_Stripe_Stripe_PriceId
                    , price = rec.price |> migrate_Stripe_Stripe_Price
                    }
                )
    , productInfo = old.productInfo |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_ProductId) migrate_Stripe_Stripe_ProductInfo
    }


migrate_Types_LoadedModel : Evergreen.V135.Types.LoadedModel -> Evergreen.V136.Types.LoadedModel
migrate_Types_LoadedModel old =
    { key = old.key
    , now = old.now
    , window =
        old.window
            |> (\rec -> rec)
    , showTooltip = old.showTooltip
    , loginForm = old.loginForm |> migrate_Token_Types_LoginForm
    , loginErrorMessage = old.loginErrorMessage
    , signInStatus = Evergreen.V136.Token.Types.NotSignedIn
    , currentUserData = old.currentUserData |> Maybe.map migrate_User_LoginData
    , prices =
        old.prices
            |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_ProductId)
                (\rec ->
                    { priceId = rec.priceId |> migrate_Id_Id migrate_Stripe_Stripe_PriceId
                    , price = rec.price |> migrate_Stripe_Stripe_Price
                    }
                )
    , productInfoDict = old.productInfoDict |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_ProductId) migrate_Stripe_Stripe_ProductInfo
    , selectedProduct = old.selectedProduct |> Maybe.map (\( t1, t2, t3 ) -> ( t1 |> migrate_Id_Id migrate_Stripe_Stripe_ProductId, t2 |> migrate_Id_Id migrate_Stripe_Stripe_PriceId, t3 |> migrate_Stripe_Product_Product_ ))
    , form = old.form |> migrate_Stripe_PurchaseForm_PurchaseForm
    , currentUser = old.currentUser |> Maybe.map migrate_User_User
    , signInState = old.signInState |> migrate_Types_SignInState
    , realname = old.realname
    , username = old.username
    , email = old.email
    , password = old.password
    , passwordConfirmation = old.passwordConfirmation
    , adminDisplay = old.adminDisplay |> migrate_Types_AdminDisplay
    , backendModel = old.backendModel |> Maybe.map migrate_Types_BackendModel
    , route = old.route |> migrate_Route_Route
    , message = old.message
    , language = old.language
    , weatherData = old.weatherData
    , inputCity = old.inputCity
    , currentKVPair = old.currentKVPair
    , keyValueStore = old.keyValueStore
    , inputKey = old.inputKey
    , inputValue = old.inputValue
    , inputFilterData = old.inputFilterData
    , kvViewType = old.kvViewType |> migrate_KeyValueStore_KVViewType
    , kvVerbosity = old.kvVerbosity |> migrate_KeyValueStore_KVVerbosity
    }


migrate_Types_LoadingModel : Evergreen.V135.Types.LoadingModel -> Evergreen.V136.Types.LoadingModel
migrate_Types_LoadingModel old =
    { key = old.key
    , now = old.now
    , window = old.window
    , route = old.route |> migrate_Route_Route
    , initData = old.initData |> Maybe.map migrate_Types_InitData2
    }


migrate_Types_SignInState : Evergreen.V135.Types.SignInState -> Evergreen.V136.Types.SignInState
migrate_Types_SignInState old =
    case old of
        Evergreen.V135.Types.SignedOut ->
            Evergreen.V136.Types.SignedOut

        Evergreen.V135.Types.SignUp ->
            Evergreen.V136.Types.SignUp

        Evergreen.V135.Types.SignedIn ->
            Evergreen.V136.Types.SignedIn


migrate_User_LoginData : Evergreen.V135.User.LoginData -> Evergreen.V136.User.LoginData
migrate_User_LoginData old =
    { username = old.username
    , role = old.role |> migrate_User_Role
    }


migrate_User_Role : Evergreen.V135.User.Role -> Evergreen.V136.User.Role
migrate_User_Role old =
    case old of
        Evergreen.V135.User.AdminRole ->
            Evergreen.V136.User.AdminRole

        Evergreen.V135.User.UserRole ->
            Evergreen.V136.User.UserRole


migrate_User_User : Evergreen.V135.User.User -> Evergreen.V136.User.User
migrate_User_User old =
    { id = old.id
    , realname = old.realname
    , username = old.username
    , email = old.email |> migrate_EmailAddress_EmailAddress
    , created_at = old.created_at
    , updated_at = old.updated_at
    , role = old.role |> migrate_User_Role
    , recentLoginEmails = old.recentLoginEmails
    }
