module Evergreen.Migrate.V138 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import AssocList
import Dict
import Evergreen.V137.Email
import Evergreen.V137.EmailAddress
import Evergreen.V137.Id
import Evergreen.V137.KeyValueStore
import Evergreen.V137.MagicToken.Types
import Evergreen.V137.Name
import Evergreen.V137.Route
import Evergreen.V137.Session
import Evergreen.V137.Stripe.Codec
import Evergreen.V137.Stripe.Product
import Evergreen.V137.Stripe.PurchaseForm
import Evergreen.V137.Stripe.Stripe
import Evergreen.V137.Types
import Evergreen.V137.User
import Evergreen.V138.Email
import Evergreen.V138.EmailAddress
import Evergreen.V138.Id
import Evergreen.V138.KeyValueStore
import Evergreen.V138.MagicToken.Types
import Evergreen.V138.Name
import Evergreen.V138.Route
import Evergreen.V138.Session
import Evergreen.V138.Stripe.Codec
import Evergreen.V138.Stripe.Product
import Evergreen.V138.Stripe.PurchaseForm
import Evergreen.V138.Stripe.Stripe
import Evergreen.V138.Types
import Evergreen.V138.User
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V137.Types.FrontendModel -> ModelMigration Evergreen.V138.Types.FrontendModel Evergreen.V138.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V137.Types.BackendModel -> ModelMigration Evergreen.V138.Types.BackendModel Evergreen.V138.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V137.Types.FrontendMsg -> MsgMigration Evergreen.V138.Types.FrontendMsg Evergreen.V138.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V137.Types.ToBackend -> MsgMigration Evergreen.V138.Types.ToBackend Evergreen.V138.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V137.Types.BackendMsg -> MsgMigration Evergreen.V138.Types.BackendMsg Evergreen.V138.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V137.Types.ToFrontend -> MsgMigration Evergreen.V138.Types.ToFrontend Evergreen.V138.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_AssocList_Dict : (a_old -> a_new) -> (b_old -> b_new) -> AssocList.Dict a_old b_old -> AssocList.Dict a_new b_new
migrate_AssocList_Dict migrate_a migrate_b old =
    old
        |> AssocList.toList
        |> List.map (Tuple.mapBoth migrate_a migrate_b)
        |> AssocList.fromList


migrate_EmailAddress_EmailAddress : Evergreen.V137.EmailAddress.EmailAddress -> Evergreen.V138.EmailAddress.EmailAddress
migrate_EmailAddress_EmailAddress old =
    case old of
        Evergreen.V137.EmailAddress.EmailAddress p0 ->
            Evergreen.V138.EmailAddress.EmailAddress p0


migrate_Email_EmailResult : Evergreen.V137.Email.EmailResult -> Evergreen.V138.Email.EmailResult
migrate_Email_EmailResult old =
    case old of
        Evergreen.V137.Email.SendingEmail ->
            Evergreen.V138.Email.SendingEmail

        Evergreen.V137.Email.EmailSuccess p0 ->
            Evergreen.V138.Email.EmailSuccess (p0 |> migrate_Email_PostmarkSendResponse)

        Evergreen.V137.Email.EmailFailed p0 ->
            Evergreen.V138.Email.EmailFailed p0


migrate_Email_PostmarkSendResponse : Evergreen.V137.Email.PostmarkSendResponse -> Evergreen.V138.Email.PostmarkSendResponse
migrate_Email_PostmarkSendResponse old =
    old


migrate_Id_Id : (a_old -> a_new) -> Evergreen.V137.Id.Id a_old -> Evergreen.V138.Id.Id a_new
migrate_Id_Id migrate_a old =
    case old of
        Evergreen.V137.Id.Id p0 ->
            Evergreen.V138.Id.Id p0


migrate_KeyValueStore_KVVerbosity : Evergreen.V137.KeyValueStore.KVVerbosity -> Evergreen.V138.KeyValueStore.KVVerbosity
migrate_KeyValueStore_KVVerbosity old =
    case old of
        Evergreen.V137.KeyValueStore.KVVerbose ->
            Evergreen.V138.KeyValueStore.KVVerbose

        Evergreen.V137.KeyValueStore.KVQuiet ->
            Evergreen.V138.KeyValueStore.KVQuiet


migrate_KeyValueStore_KVViewType : Evergreen.V137.KeyValueStore.KVViewType -> Evergreen.V138.KeyValueStore.KVViewType
migrate_KeyValueStore_KVViewType old =
    case old of
        Evergreen.V137.KeyValueStore.KVRaw ->
            Evergreen.V138.KeyValueStore.KVRaw

        Evergreen.V137.KeyValueStore.KVVSummary ->
            Evergreen.V138.KeyValueStore.KVVSummary

        Evergreen.V137.KeyValueStore.KVVKey ->
            Evergreen.V138.KeyValueStore.KVVKey


migrate_Name_Name : Evergreen.V137.Name.Name -> Evergreen.V138.Name.Name
migrate_Name_Name old =
    case old of
        Evergreen.V137.Name.Name p0 ->
            Evergreen.V138.Name.Name p0


migrate_Route_Route : Evergreen.V137.Route.Route -> Evergreen.V138.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V137.Route.HomepageRoute ->
            Evergreen.V138.Route.HomepageRoute

        Evergreen.V137.Route.DataStore ->
            Evergreen.V138.Route.DataStore

        Evergreen.V137.Route.EditData ->
            Evergreen.V138.Route.EditData

        Evergreen.V137.Route.Features ->
            Evergreen.V138.Route.Features

        Evergreen.V137.Route.TermsOfServiceRoute ->
            Evergreen.V138.Route.TermsOfServiceRoute

        Evergreen.V137.Route.Notes ->
            Evergreen.V138.Route.Notes

        Evergreen.V137.Route.SignInRoute ->
            Evergreen.V138.Route.SignInRoute

        Evergreen.V137.Route.Brillig ->
            Evergreen.V138.Route.Brillig

        Evergreen.V137.Route.AdminRoute ->
            Evergreen.V138.Route.AdminRoute

        Evergreen.V137.Route.Purchase ->
            Evergreen.V138.Route.Purchase

        Evergreen.V137.Route.PaymentSuccessRoute p0 ->
            Evergreen.V138.Route.PaymentSuccessRoute (p0 |> Maybe.map migrate_EmailAddress_EmailAddress)

        Evergreen.V137.Route.PaymentCancelRoute ->
            Evergreen.V138.Route.PaymentCancelRoute


migrate_Session_Interaction : Evergreen.V137.Session.Interaction -> Evergreen.V138.Session.Interaction
migrate_Session_Interaction old =
    case old of
        Evergreen.V137.Session.ISignIn p0 ->
            Evergreen.V138.Session.ISignIn p0

        Evergreen.V137.Session.ISignOut p0 ->
            Evergreen.V138.Session.ISignOut p0

        Evergreen.V137.Session.ISignUp p0 ->
            Evergreen.V138.Session.ISignUp p0


migrate_Session_SessionInfo : Evergreen.V137.Session.SessionInfo -> Evergreen.V138.Session.SessionInfo
migrate_Session_SessionInfo old =
    old |> Dict.map (\k -> migrate_Session_Interaction)


migrate_Stripe_Codec_Order : Evergreen.V137.Stripe.Codec.Order -> Evergreen.V138.Stripe.Codec.Order
migrate_Stripe_Codec_Order old =
    { priceId = old.priceId |> migrate_Id_Id migrate_Stripe_Stripe_PriceId
    , submitTime = old.submitTime
    , form = old.form |> migrate_Stripe_PurchaseForm_PurchaseFormValidated
    , emailResult = old.emailResult |> migrate_Email_EmailResult
    }


migrate_Stripe_Codec_PendingOrder : Evergreen.V137.Stripe.Codec.PendingOrder -> Evergreen.V138.Stripe.Codec.PendingOrder
migrate_Stripe_Codec_PendingOrder old =
    { priceId = old.priceId |> migrate_Id_Id migrate_Stripe_Stripe_PriceId
    , submitTime = old.submitTime
    , form = old.form |> migrate_Stripe_PurchaseForm_PurchaseFormValidated
    , sessionId = old.sessionId
    }


migrate_Stripe_Codec_Price2 : Evergreen.V137.Stripe.Codec.Price2 -> Evergreen.V138.Stripe.Codec.Price2
migrate_Stripe_Codec_Price2 old =
    { priceId = old.priceId |> migrate_Id_Id migrate_Stripe_Stripe_PriceId
    , price = old.price |> migrate_Stripe_Stripe_Price
    }


migrate_Stripe_Product_Product_ : Evergreen.V137.Stripe.Product.Product_ -> Evergreen.V138.Stripe.Product.Product_
migrate_Stripe_Product_Product_ old =
    old


migrate_Stripe_PurchaseForm_PressedSubmit : Evergreen.V137.Stripe.PurchaseForm.PressedSubmit -> Evergreen.V138.Stripe.PurchaseForm.PressedSubmit
migrate_Stripe_PurchaseForm_PressedSubmit old =
    case old of
        Evergreen.V137.Stripe.PurchaseForm.PressedSubmit ->
            Evergreen.V138.Stripe.PurchaseForm.PressedSubmit

        Evergreen.V137.Stripe.PurchaseForm.NotPressedSubmit ->
            Evergreen.V138.Stripe.PurchaseForm.NotPressedSubmit


migrate_Stripe_PurchaseForm_PurchaseData : Evergreen.V137.Stripe.PurchaseForm.PurchaseData -> Evergreen.V138.Stripe.PurchaseForm.PurchaseData
migrate_Stripe_PurchaseForm_PurchaseData old =
    { billingName = old.billingName |> migrate_Name_Name
    , billingEmail = old.billingEmail |> migrate_EmailAddress_EmailAddress
    }


migrate_Stripe_PurchaseForm_PurchaseForm : Evergreen.V137.Stripe.PurchaseForm.PurchaseForm -> Evergreen.V138.Stripe.PurchaseForm.PurchaseForm
migrate_Stripe_PurchaseForm_PurchaseForm old =
    { submitStatus = old.submitStatus |> migrate_Stripe_PurchaseForm_SubmitStatus
    , name = old.name
    , billingEmail = old.billingEmail
    , country = old.country
    }


migrate_Stripe_PurchaseForm_PurchaseFormValidated : Evergreen.V137.Stripe.PurchaseForm.PurchaseFormValidated -> Evergreen.V138.Stripe.PurchaseForm.PurchaseFormValidated
migrate_Stripe_PurchaseForm_PurchaseFormValidated old =
    case old of
        Evergreen.V137.Stripe.PurchaseForm.ImageCreditPurchase p0 ->
            Evergreen.V138.Stripe.PurchaseForm.ImageCreditPurchase (p0 |> migrate_Stripe_PurchaseForm_PurchaseData)

        Evergreen.V137.Stripe.PurchaseForm.ImageLibraryPackagePurchase p0 ->
            Evergreen.V138.Stripe.PurchaseForm.ImageLibraryPackagePurchase (p0 |> migrate_Stripe_PurchaseForm_PurchaseData)


migrate_Stripe_PurchaseForm_SubmitStatus : Evergreen.V137.Stripe.PurchaseForm.SubmitStatus -> Evergreen.V138.Stripe.PurchaseForm.SubmitStatus
migrate_Stripe_PurchaseForm_SubmitStatus old =
    case old of
        Evergreen.V137.Stripe.PurchaseForm.NotSubmitted p0 ->
            Evergreen.V138.Stripe.PurchaseForm.NotSubmitted (p0 |> migrate_Stripe_PurchaseForm_PressedSubmit)

        Evergreen.V137.Stripe.PurchaseForm.Submitting ->
            Evergreen.V138.Stripe.PurchaseForm.Submitting

        Evergreen.V137.Stripe.PurchaseForm.SubmitBackendError p0 ->
            Evergreen.V138.Stripe.PurchaseForm.SubmitBackendError p0


migrate_Stripe_Stripe_Price : Evergreen.V137.Stripe.Stripe.Price -> Evergreen.V138.Stripe.Stripe.Price
migrate_Stripe_Stripe_Price old =
    old


migrate_Stripe_Stripe_PriceId : Evergreen.V137.Stripe.Stripe.PriceId -> Evergreen.V138.Stripe.Stripe.PriceId
migrate_Stripe_Stripe_PriceId old =
    case old of
        Evergreen.V137.Stripe.Stripe.PriceId p0 ->
            Evergreen.V138.Stripe.Stripe.PriceId p0


migrate_Stripe_Stripe_ProductId : Evergreen.V137.Stripe.Stripe.ProductId -> Evergreen.V138.Stripe.Stripe.ProductId
migrate_Stripe_Stripe_ProductId old =
    case old of
        Evergreen.V137.Stripe.Stripe.ProductId p0 ->
            Evergreen.V138.Stripe.Stripe.ProductId p0


migrate_Stripe_Stripe_ProductInfo : Evergreen.V137.Stripe.Stripe.ProductInfo -> Evergreen.V138.Stripe.Stripe.ProductInfo
migrate_Stripe_Stripe_ProductInfo old =
    old


migrate_Stripe_Stripe_ProductInfoDict : Evergreen.V137.Stripe.Stripe.ProductInfoDict -> Evergreen.V138.Stripe.Stripe.ProductInfoDict
migrate_Stripe_Stripe_ProductInfoDict old =
    old |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_ProductId) migrate_Stripe_Stripe_ProductInfo


migrate_Stripe_Stripe_StripeSessionId : Evergreen.V137.Stripe.Stripe.StripeSessionId -> Evergreen.V138.Stripe.Stripe.StripeSessionId
migrate_Stripe_Stripe_StripeSessionId old =
    case old of
        Evergreen.V137.Stripe.Stripe.StripeSessionId p0 ->
            Evergreen.V138.Stripe.Stripe.StripeSessionId p0


migrate_Token_Types_EnterEmail2 : Evergreen.V137.MagicToken.Types.EnterEmail2 -> Evergreen.V138.MagicToken.Types.EnterEmail2
migrate_Token_Types_EnterEmail2 old =
    old


migrate_Token_Types_EnterLoginCode2 : Evergreen.V137.MagicToken.Types.EnterLoginCode2 -> Evergreen.V138.MagicToken.Types.EnterLoginCode2
migrate_Token_Types_EnterLoginCode2 old =
    { sentTo = old.sentTo |> migrate_EmailAddress_EmailAddress
    , loginCode = old.loginCode
    , attempts = old.attempts |> Dict.map (\k -> migrate_Token_Types_LoginCodeStatus)
    }


migrate_Token_Types_Log : Evergreen.V137.MagicToken.Types.Log -> Evergreen.V138.MagicToken.Types.Log
migrate_Token_Types_Log old =
    old |> List.map (Tuple.mapSecond migrate_Token_Types_LogItem)


migrate_Token_Types_LogItem : Evergreen.V137.MagicToken.Types.LogItem -> Evergreen.V138.MagicToken.Types.LogItem
migrate_Token_Types_LogItem old =
    case old of
        Evergreen.V137.MagicToken.Types.LoginsRateLimited p0 ->
            Evergreen.V138.MagicToken.Types.LoginsRateLimited p0

        Evergreen.V137.MagicToken.Types.FailedToCreateLoginCode p0 ->
            Evergreen.V138.MagicToken.Types.FailedToCreateLoginCode p0


migrate_Token_Types_LoginCodeStatus : Evergreen.V137.MagicToken.Types.LoginCodeStatus -> Evergreen.V138.MagicToken.Types.LoginCodeStatus
migrate_Token_Types_LoginCodeStatus old =
    case old of
        Evergreen.V137.MagicToken.Types.Checking ->
            Evergreen.V138.MagicToken.Types.Checking

        Evergreen.V137.MagicToken.Types.NotValid ->
            Evergreen.V138.MagicToken.Types.NotValid


migrate_Token_Types_LoginForm : Evergreen.V137.MagicToken.Types.LoginForm -> Evergreen.V138.MagicToken.Types.LoginForm
migrate_Token_Types_LoginForm old =
    case old of
        Evergreen.V137.MagicToken.Types.EnterEmail p0 ->
            Evergreen.V138.MagicToken.Types.EnterEmail (p0 |> migrate_Token_Types_EnterEmail2)

        Evergreen.V137.MagicToken.Types.EnterLoginCode p0 ->
            Evergreen.V138.MagicToken.Types.EnterLoginCode (p0 |> migrate_Token_Types_EnterLoginCode2)


migrate_Token_Types_SignInStatus : Evergreen.V137.MagicToken.Types.SignInStatus -> Evergreen.V138.MagicToken.Types.SignInStatus
migrate_Token_Types_SignInStatus old =
    case old of
        Evergreen.V137.MagicToken.Types.NotSignedIn ->
            Evergreen.V138.MagicToken.Types.NotSignedIn

        Evergreen.V137.MagicToken.Types.SigningUp ->
            Evergreen.V138.MagicToken.Types.SigningUp

        Evergreen.V137.MagicToken.Types.SignedIn ->
            Evergreen.V138.MagicToken.Types.SignedIn


migrate_Types_AdminDisplay : Evergreen.V137.Types.AdminDisplay -> Evergreen.V138.Types.AdminDisplay
migrate_Types_AdminDisplay old =
    case old of
        Evergreen.V137.Types.ADStripe ->
            Evergreen.V138.Types.ADStripe

        Evergreen.V137.Types.ADUser ->
            Evergreen.V138.Types.ADUser

        Evergreen.V137.Types.ADSession ->
            Evergreen.V138.Types.ADSession

        Evergreen.V137.Types.ADKeyValues ->
            Evergreen.V138.Types.ADKeyValues


migrate_Types_BackendDataStatus : Evergreen.V137.Types.BackendDataStatus -> Evergreen.V138.Types.BackendDataStatus
migrate_Types_BackendDataStatus old =
    case old of
        Evergreen.V137.Types.Fubar ->
            Evergreen.V138.Types.Fubar

        Evergreen.V137.Types.Sunny ->
            Evergreen.V138.Types.Sunny

        Evergreen.V137.Types.LoadedBackendData ->
            Evergreen.V138.Types.LoadedBackendData


migrate_Types_BackendModel : Evergreen.V137.Types.BackendModel -> Evergreen.V138.Types.BackendModel
migrate_Types_BackendModel old =
    { randomAtmosphericNumbers = old.randomAtmosphericNumbers
    , localUuidData = old.localUuidData
    , time = old.time
    , secretCounter = old.secretCounter
    , sessionDict = old.sessionDict
    , pendingLogins =
        old.pendingLogins
            |> migrate_AssocList_Dict identity
                (\rec ->
                    { loginAttempts = rec.loginAttempts
                    , emailAddress = rec.emailAddress |> migrate_EmailAddress_EmailAddress
                    , creationTime = rec.creationTime
                    , loginCode = rec.loginCode
                    }
                )
    , log = old.log |> migrate_Token_Types_Log
    , userDictionary = old.userDictionary |> Dict.map (\k -> migrate_User_User)
    , sessions = old.sessions
    , sessionInfo = old.sessionInfo |> migrate_Session_SessionInfo
    , orders = old.orders |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_StripeSessionId) migrate_Stripe_Codec_Order
    , pendingOrder = old.pendingOrder |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_StripeSessionId) migrate_Stripe_Codec_PendingOrder
    , expiredOrders = old.expiredOrders |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_StripeSessionId) migrate_Stripe_Codec_PendingOrder
    , prices = old.prices |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_ProductId) migrate_Stripe_Codec_Price2
    , products = old.products |> migrate_Stripe_Stripe_ProductInfoDict
    , keyValueStore = old.keyValueStore
    }


migrate_Types_FrontendModel : Evergreen.V137.Types.FrontendModel -> Evergreen.V138.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V137.Types.Loading p0 ->
            Evergreen.V138.Types.Loading (p0 |> migrate_Types_LoadingModel)

        Evergreen.V137.Types.Loaded p0 ->
            Evergreen.V138.Types.Loaded (p0 |> migrate_Types_LoadedModel)


migrate_Types_InitData2 : Evergreen.V137.Types.InitData2 -> Evergreen.V138.Types.InitData2
migrate_Types_InitData2 old =
    { prices =
        old.prices
            |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_ProductId)
                (\rec ->
                    { priceId = rec.priceId |> migrate_Id_Id migrate_Stripe_Stripe_PriceId
                    , price = rec.price |> migrate_Stripe_Stripe_Price
                    }
                )
    , productInfo = old.productInfo |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_ProductId) migrate_Stripe_Stripe_ProductInfo
    }


migrate_Types_LoadedModel : Evergreen.V137.Types.LoadedModel -> Evergreen.V138.Types.LoadedModel
migrate_Types_LoadedModel old =
    { key = old.key
    , now = old.now
    , window =
        old.window
            |> (\rec -> rec)
    , showTooltip = old.showTooltip
    , loginForm = old.loginForm |> migrate_Token_Types_LoginForm
    , loginErrorMessage = old.loginErrorMessage
    , signInStatus = old.signInStatus |> migrate_Token_Types_SignInStatus
    , currentUserData = old.currentUserData |> Maybe.map migrate_User_LoginData
    , prices =
        old.prices
            |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_ProductId)
                (\rec ->
                    { priceId = rec.priceId |> migrate_Id_Id migrate_Stripe_Stripe_PriceId
                    , price = rec.price |> migrate_Stripe_Stripe_Price
                    }
                )
    , productInfoDict = old.productInfoDict |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_Stripe_ProductId) migrate_Stripe_Stripe_ProductInfo
    , selectedProduct = old.selectedProduct |> Maybe.map (\( t1, t2, t3 ) -> ( t1 |> migrate_Id_Id migrate_Stripe_Stripe_ProductId, t2 |> migrate_Id_Id migrate_Stripe_Stripe_PriceId, t3 |> migrate_Stripe_Product_Product_ ))
    , form = old.form |> migrate_Stripe_PurchaseForm_PurchaseForm
    , currentUser = old.currentUser |> Maybe.map migrate_User_User
    , signInState = old.signInState |> migrate_Types_SignInState
    , realname = old.realname
    , username = old.username
    , email = old.email
    , password = old.password
    , passwordConfirmation = old.passwordConfirmation
    , adminDisplay = old.adminDisplay |> migrate_Types_AdminDisplay
    , backendModel = old.backendModel |> Maybe.map migrate_Types_BackendModel
    , route = old.route |> migrate_Route_Route
    , message = old.message
    , language = old.language
    , weatherData = old.weatherData
    , inputCity = old.inputCity
    , currentKVPair = old.currentKVPair
    , keyValueStore = old.keyValueStore
    , inputKey = old.inputKey
    , inputValue = old.inputValue
    , inputFilterData = old.inputFilterData
    , kvViewType = old.kvViewType |> migrate_KeyValueStore_KVViewType
    , kvVerbosity = old.kvVerbosity |> migrate_KeyValueStore_KVVerbosity
    }


migrate_Types_LoadingModel : Evergreen.V137.Types.LoadingModel -> Evergreen.V138.Types.LoadingModel
migrate_Types_LoadingModel old =
    { key = old.key
    , now = old.now
    , window = old.window
    , route = old.route |> migrate_Route_Route
    , initData = old.initData |> Maybe.map migrate_Types_InitData2
    }


migrate_Types_SignInState : Evergreen.V137.Types.SignInState -> Evergreen.V138.Types.SignInState
migrate_Types_SignInState old =
    case old of
        Evergreen.V137.Types.SignedOut ->
            Evergreen.V138.Types.SignedOut

        Evergreen.V137.Types.SignUp ->
            Evergreen.V138.Types.SignUp

        Evergreen.V137.Types.SignedIn ->
            Evergreen.V138.Types.SignedIn


migrate_Types_ToFrontend : Evergreen.V137.Types.ToFrontend -> Evergreen.V138.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V137.Types.InitData p0 ->
            Evergreen.V138.Types.InitData (p0 |> migrate_Types_InitData2)

        Evergreen.V137.Types.GotMessage p0 ->
            Evergreen.V138.Types.GotMessage p0

        Evergreen.V137.Types.SubmitFormResponse p0 ->
            Evergreen.V138.Types.SubmitFormResponse (p0 |> Result.map (migrate_Id_Id migrate_Stripe_Stripe_StripeSessionId))

        Evergreen.V137.Types.AdminInspectResponse p0 ->
            Evergreen.V138.Types.AdminInspectResponse (p0 |> migrate_Types_BackendModel)

        Evergreen.V137.Types.CheckLoginResponse p0 ->
            Evergreen.V138.Types.CheckLoginResponse (p0 |> Result.mapError migrate_Types_BackendDataStatus >> Result.map migrate_User_LoginData)

        Evergreen.V137.Types.LoginWithTokenResponse p0 ->
            Evergreen.V138.Types.LoginWithTokenResponse (p0 |> Result.map migrate_User_LoginData)

        Evergreen.V137.Types.GetLoginTokenRateLimited ->
            Evergreen.V138.Types.GetLoginTokenRateLimited

        Evergreen.V137.Types.LoggedOutSession ->
            Evergreen.V138.Types.LoggedOutSession

        Evergreen.V137.Types.SignInError p0 ->
            Evergreen.V138.Types.SignInError p0

        Evergreen.V137.Types.UserSignedIn p0 ->
            Evergreen.V138.Types.UserSignedIn (p0 |> Maybe.map migrate_User_User)

        Evergreen.V137.Types.ReceivedWeatherData p0 ->
            Evergreen.V138.Types.ReceivedWeatherData p0

        Evergreen.V137.Types.GotKeyValueStore p0 ->
            Evergreen.V138.Types.GotKeyValueStore p0

        Evergreen.V137.Types.GotBackendModel p0 ->
            Evergreen.V138.Types.GotBackendModel (p0 |> migrate_Types_BackendModel)


migrate_User_LoginData : Evergreen.V137.User.LoginData -> Evergreen.V138.User.LoginData
migrate_User_LoginData old =
    { username = old.username
    , role = old.role |> migrate_User_Role
    }


migrate_User_Role : Evergreen.V137.User.Role -> Evergreen.V138.User.Role
migrate_User_Role old =
    case old of
        Evergreen.V137.User.AdminRole ->
            Evergreen.V138.User.AdminRole

        Evergreen.V137.User.UserRole ->
            Evergreen.V138.User.UserRole


migrate_User_User : Evergreen.V137.User.User -> Evergreen.V138.User.User
migrate_User_User old =
    { id = old.id
    , realname = old.realname
    , username = old.username
    , email = old.email |> migrate_EmailAddress_EmailAddress
    , created_at = old.created_at
    , updated_at = old.updated_at
    , role = old.role |> migrate_User_Role
    , recentLoginEmails = old.recentLoginEmails
    }
